version: '3'

services:
  node_serve:
    build: .
    container_name: serve
    ports:
      - "80:8080"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    depends_on: 
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
      - 27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: movies
#    volumes:
#      - ./data/db:/data/db
#  es:
#    image: elasticsearch:7.6.0
#    container_name: es
